### PR TITLE
Make loading indicator display earlier

### PR DESCRIPTION
**Pull request by jmelot**
You won't be able to see this locally, but as the data has grown in size it's become apparent that the loading indicator is not showing as early as it needs to be. I'm not sure why, I think the way we are using Suspense is correct, but here's a quick stopgap until we come up with a better way (like improving how data is fed to the app...)

Also bumps data

### CODE REVIEW

**Review by brianlove — APPROVED** [review]
👍

**Comment by jmelot** [comment]
Thank you!

**Review by brianlove — CHANGES_REQUESTED** [review]
Loading fix looks good, but there are a few issues:

Several of the changes in Percy are clearly due to the data update, but there's also a case in 'Top cited articles' where the subjects/topics are no longer included:

| Old | New |
| --- | --- |
| image | image |

The Python tests also fail, preventing Jest from running (6 Jest tests in one suite fail locally):
> A module that was compiled using NumPy 1.x cannot be run in
> NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
> versions of NumPy, modules must be compiled with NumPy 2.0.
> Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

**Comment by jmelot** [comment]
Yeah the arXiv subject thing is fine, that's because we consolidated venue names. I'm looking at the test failures now... it runs fine locally so it's something about the github actions configuration

**Pull request merged**
